import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import stylesFigure from "@/styles/figure.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Chatbot IA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen min-h-screen relative container mx-auto flex-col items-center p-16">
          {children}
          <div className={`absolute rounded top-0 right-40 h-16 w-16 ${stylesFigure.bgFigure1}`}>
          </div>
          <div className={`absolute rounded top-0 left-20 h-16 w-16 ${stylesFigure.bgFigure1}`}>
          </div>
        </main>
      </body>
    </html>
  );
}
